import type { createAdminClient } from './supabase-admin.ts';

type AdminClient = ReturnType<typeof createAdminClient>;

export function shortJobKey(jobId: string): string {
  return jobId.replace(/-/g, '').slice(0, 8);
}

export function parseTailoredJobKey(name: string): string | null {
  const match = name.trim().match(/\(([0-9a-f]{8})\)\s*$/i);
  return match?.[1]?.toLowerCase() ?? null;
}

export function resumeStorageFileName(fileName: string): string {
  const base = String(fileName || 'resume.pdf').split(/[/\\]/).pop()?.trim() || 'resume.pdf';
  const cleaned = base.replace(/[^a-zA-Z0-9._-]/g, '').replace(/^\.+/, '') || 'resume.pdf';
  return /\.pdf$/i.test(cleaned) ? cleaned : `${cleaned}.pdf`;
}

export function resumeStorageObjectPath(userId: string, fileName: string): string {
  return `${userId}/resumes/${resumeStorageFileName(fileName)}`;
}

export function storedFileNameFromOutput(output: unknown): string {
  if (!output || typeof output !== 'object') return '';
  const row = output as Record<string, unknown>;
  if (row.skipped) return '';
  const named = String(row.fileName || '').trim();
  if (named) return resumeStorageFileName(named);
  const path = String(row.storage_path || '').trim();
  if (!path) return '';
  return resumeStorageFileName(path.split('/').pop() || '');
}

export function storedFileLogMessage(fileName: string): string {
  return `Stored file: ${resumeStorageFileName(fileName)}`;
}

export function storedFileLogMessages(output: unknown): string[] {
  const items = Array.isArray(output) ? output : [output];
  const messages: string[] = [];
  for (const item of items) {
    const name = storedFileNameFromOutput(item);
    if (name) messages.push(storedFileLogMessage(name));
  }
  return messages;
}

/** `Tailored: Company Role (jobKey)` — job key keeps two postings of the same role distinct. */
export function buildTailoredResumeName(company: string, role: string, jobId?: string): string {
  const suffix = jobId ? ` (${shortJobKey(jobId)})` : '';
  const prefix = 'Tailored: ';
  const maxBase = Math.max(8, 120 - prefix.length - suffix.length);
  const base = `${company} ${role}`.replace(/\s+/g, ' ').trim().slice(0, maxBase).trim();
  return `${prefix}${base}${suffix}`;
}

export async function appendResumeVersion(
  admin: AdminClient,
  userId: string,
  resumeId: string,
  content: string,
  atsScore = 0,
  note?: string,
): Promise<number> {
  const { data: latest, error: latestError } = await admin
    .from('resume_versions')
    .select('version, content')
    .eq('resume_id', resumeId)
    .eq('user_id', userId)
    .order('version', { ascending: false })
    .limit(1);
  if (latestError) throw latestError;

  const latestRow = latest?.[0];
  if (latestRow && String(latestRow.content || '') === content) {
    return Number(latestRow.version ?? 1);
  }

  const nextVersion = Number(latestRow?.version ?? 0) + 1;
  const { error } = await admin.from('resume_versions').insert({
    user_id: userId,
    resume_id: resumeId,
    version: nextVersion,
    content,
    ats_score: atsScore,
    note: note ?? null,
  });
  if (error) throw error;
  return nextVersion;
}

export async function upsertTailoredResume(
  admin: AdminClient,
  userId: string,
  input: { jobId?: string; company: string; role: string; content: string },
): Promise<string> {
  const name = buildTailoredResumeName(input.company, input.role, input.jobId);
  const now = new Date().toISOString();

  if (input.jobId) {
    const { data: byJob } = await admin
      .from('resumes')
      .select('id, content, ats_score')
      .eq('user_id', userId)
      .eq('job_id', input.jobId)
      .maybeSingle();
    if (byJob?.id) {
      const resumeId = String(byJob.id);
      const contentChanged = String(byJob.content || '') !== input.content;
      await admin.from('resumes').update({
        name,
        content: input.content,
        updated_at: now,
      }).eq('id', resumeId);
      if (contentChanged) {
        await appendResumeVersion(
          admin,
          userId,
          resumeId,
          input.content,
          Number(byJob.ats_score ?? 0),
          'Generated by workflow',
        );
      }
      return resumeId;
    }
  } else {
    const { data: byName } = await admin
      .from('resumes')
      .select('id, content, ats_score')
      .eq('user_id', userId)
      .eq('name', name)
      .maybeSingle();
    if (byName?.id) {
      const resumeId = String(byName.id);
      const contentChanged = String(byName.content || '') !== input.content;
      await admin.from('resumes').update({
        content: input.content,
        updated_at: now,
      }).eq('id', resumeId);
      if (contentChanged) {
        await appendResumeVersion(
          admin,
          userId,
          resumeId,
          input.content,
          Number(byName.ats_score ?? 0),
          'Generated by workflow',
        );
      }
      return resumeId;
    }
  }

  const { data: created, error } = await admin.from('resumes').insert({
    user_id: userId,
    name,
    type: 'technical',
    content: input.content,
    ats_score: 0,
    job_id: input.jobId || null,
  }).select('id').single();
  if (error) throw error;
  const resumeId = String(created.id);
  await appendResumeVersion(admin, userId, resumeId, input.content, 0, 'Generated by workflow');
  return resumeId;
}

export async function linkResumePdf(
  admin: AdminClient,
  resumeId: string,
  input: { storagePath: string; pdfUrl?: string },
): Promise<void> {
  const patch: Record<string, unknown> = {
    storage_path: input.storagePath,
    updated_at: new Date().toISOString(),
  };
  if (input.pdfUrl) patch.pdf_url = input.pdfUrl;
  const { error } = await admin.from('resumes').update(patch).eq('id', resumeId);
  if (error) throw error;
}

export async function markResumeDriveSync(
  admin: AdminClient,
  resumeId: string,
  driveFileId: string,
): Promise<void> {
  const { error } = await admin.from('resumes').update({
    drive_file_id: driveFileId,
    drive_synced_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  }).eq('id', resumeId);
  if (error) throw error;
}
